import Head from "next/head";
import styles from "./MainLayout.module.css";
import { Inter } from 'next/font/google'

import { Navbar } from "../Navbar";

const inter = Inter({ subsets: ['latin'] })
type MisProps = {
  children: React.ReactNode; // 👈️ type children
};

export const MainLayout = ({children}: MisProps) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Navbar />
          <main className={`${styles.main} ${inter.className}`}>
            
            {children}
            
          </main>
        </div>
      )
}
